/run/initialize
/run/verbose 0
/tracking/verbose 0
/event/verbose 0

/vis/open OGL 600x600-0+0
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh 1
/vis/drawVolume
/vis/scene/add/extent
/vis/scene/endOfEventAction accumulate
/vis/scene/add/scale 10 cm
/vis/scene/add/axes

/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID

/vis/modeling/trajectories/drawByParticleID-0/set gamma red
/vis/modeling/trajectories/drawByParticleID/set e- blue
/vis/modeling/trajectories/drawByParticleID/set e+ yellow
/vis/modeling/trajectories/drawByParticleID/set opticalphoton cyan
/run/initialize
/run/verbose 0
/tracking/verbose 0

/vis/verbose 2
/vis/disable
/vis/enable

/vis/open OGL 600x600-0+0
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh 1
/vis/drawVolume
/vis/scene/add/extent
/vis/scene/endOfEventAction accumulate
/vis/scene/add/scale 10 cm
/vis/scene/add/axes

/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/list
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/set drawByParticleID

/vis/modeling/trajectories/drawByParticleID/set gamma red
/vis/modeling/trajectories/drawByParticleID/set e- blue
/vis/modeling/trajectories/drawByParticleID/set e+ yellow
/vis/modeling/trajectories/drawByParticleID/set opticalphoton cyan

/vis/scene/notifyHandlers
/vis/viewer/rebuild
/vis/viewer/refresh

/vis/scene/notifyHandlers
/vis/viewer/rebuild
/vis/viewer/refresh
